### ISSUE TITLE
Counry Code Error

### ISSUE THREAD

**Issue by JatinPardeshi** [Chr0m0s0m3s/DeadTrap#11]
I got this error......

Running Scan...Traceback (most recent call last):
  File "main.py", line 109, in <module>
    browser.get(f"https://www.truecaller.com/search/{str(answer['country_code']).lower()}/{query.replace('+91', '')}")
KeyError: 'country_code'

**Comment by iiaosmal** [comment]
Me too and I didn't find any solution

**Comment by mssalvatore** [comment]
I did some digging. DeadTrap makes a query to [request = `http://apilayer.net/api/validate?access_key={api_key}&number={query}`](https://github.com/Chr0m0s0m3s/DeadTrap/blob/b322c0700b474bb72e54fbafcc91cb0996e9cc68/main.py#L100), which returns this:

```json
{
  "success": false,
  "error": {
    "code": 104,
    "info": "Your monthly usage limit has been reached. Please upgrade your Subscription Plan."
  }
}
```

DeadTrap Then tries to pull the country_code key out of that response, but, of course, it's nonexistant.

DeadTrap should provide instructions so that users can register with the API service and provide their own API keys.

**Comment by JatinPardeshi** [comment]
Will find an alternative for this.....

**Comment by Chr0m0s0m3s** [comment]
Solved....the api wont trouble anymore
